use actix_web::{HttpMessage, HttpRequest, HttpResponse, Responder,web, get,};
use serde::Serialize;
use sqlx::PgPool;
use crate::middleware::auth_middleware::Claims;
use crate::state::AppState;
use sqlx::FromRow;
use sqlx::types::time::OffsetDateTime;
use sqlx::{Postgres, QueryBuilder};





//================DTOs OR Data Transfer Objects.=======================

// Full dashboard response structure returned to frontend
// Matches the DashboardSummary interface in frontend TypeScript
#[derive(Serialize)]
#[allow(dead_code)]
pub struct DashboardSummary {

    // Total revenue from all matching orders
    pub total_revenue: f64,

    // Total quantity of all products sold
    pub total_quantity_sold: i64,

    // Total number of completed orders
    pub total_sold: i64,

    // Average value of each order
    pub avg_order_value: f64,

    // Top 5 best-selling products
    pub top_products: Vec<TopProduct>,

    // Most recent transactions
    pub recent_transactions: Vec<RecentTransaction>,

    // Products with low stock
    pub low_stock: Vec<LowStockItem>,
}

// Struct used for totals query result
#[derive(sqlx::FromRow)]
pub struct TotalsRow {

    // Total revenue from query
    pub total_revenue: f64,

    // Number of orders
    pub total_orders: i64,

    // Average order value
    pub avg_order_value: f64,
}

// Struct used for total sold query result
#[derive(sqlx::FromRow)]
pub struct TotalSoldRow {

    // Total quantity sold
    pub total_sold: i64,
}

// Top 5 products ranked by quantity sold
#[derive(Debug, Serialize, FromRow)]
pub struct TopProduct {

    // Product name
    pub name: String,

    // Total quantity sold
    pub quantity: i64,

    // Total revenue generated by product
    pub revenue: f64,
}

// Last 10 orders sorted by newest first
#[derive(sqlx::FromRow, serde::Serialize, serde::Deserialize)]
pub struct RecentTransaction {

    // Order ID
    pub id: i32,

    // Date and time order was created
    #[serde(with = "time::serde::iso8601")]
    pub created_at: OffsetDateTime,

    // Total number of items in order
    pub items: i64,

    // Total order amount
    pub total: f64,
}

// Products with low stock levels
#[derive(Debug, Serialize, FromRow)]
pub struct LowStockItem {

    // Product name
    pub name: String,

    // Remaining stock count
    pub stock: i32,
}

// Query parameters received from frontend
#[derive(serde::Deserialize)]
pub struct DashboardQuery {
    // Optional date range filter
    // Example: day, week, month
    pub range: Option<String>,

}

//=====================================================================




//====================SERVICE STRUCT (OOP-LIKE DESIGN)======================

// Service struct containing database pool
#[derive(Clone)]
pub struct DashboardService {

    // PostgreSQL connection pool
    pool: PgPool,
}

//====================================================================




//=====================ERROR HANDLING ENUM============================

// Custom application errors
#[derive(Debug)]
pub enum CustomError {

    // Database query failed
    DatabaseError,

    // User is not authorized
    Unauthorized,
}

// Convert enum errors into readable messages
impl std::fmt::Display for CustomError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {

        // Match enum variants to string messages
        let msg = match self {
            CustomError::DatabaseError => "Database error",
            CustomError::Unauthorized => "Unauthorized",
        };

        // Return formatted error message
        write!(f, "{}", msg)
    }
}

//====================================================================




//============OOP METHODS OR STRUCT IMPLEMENTATION IN RUST============

impl DashboardService {

    // Constructor function for DashboardService
    pub fn new(pool: PgPool) -> Self {

        // Return new service instance
        Self{pool}
    }

    // ============================================================
    // ORDER FILTERS
    // Used for:
    // - totals
    // - total sold
    // - top products
    // - recent transactions
    // ============================================================

    // Reusable function for filtering order queries
    // based on role and time range
    fn apply_order_filters(
        query: &mut QueryBuilder<Postgres>,
        claim: &Claims,
        range: &Option<String>,
    ) -> Result<(), CustomError> {

        // ================= ROLE FILTERS =================

        // Apply role-based access restrictions
        match claim.role.as_str() {

            // Admin can see all company orders
            "admin" => {
                query.push(" WHERE company_info.company_name = ");
                query.push_bind(claim.companyname.clone());
            }

            // Manager can only see orders from their branch
            "manager" => {
                query.push(" WHERE company_info.company_name = ");
                query.push_bind(claim.companyname.clone());

                query.push(" AND company_info.branch_name = ");
                query.push_bind(claim.branchname.clone());
            }

            // POS staff can only see their own orders
            "pos_staff" => {
                query.push(" WHERE company_info.company_name = ");
                query.push_bind(claim.companyname.clone());

                query.push(" AND company_info.branch_name = ");
                query.push_bind(claim.branchname.clone());

                query.push(" AND orders.user_id = ");
                query.push_bind(claim.id.clone());
            }

            // Reject invalid roles
            _ => {
                return Err(CustomError::Unauthorized);
            }
        }

        // ================= TIME FILTERS =================

        // Apply optional date range filters
        match range.as_deref() {

            // Filter today's orders
            Some("day") => {
                query.push(
                    " AND orders.created_at >= date_trunc('day', NOW())"
                );
            }

            // Filter this week's orders
            Some("week") => {
                query.push(
                    " AND orders.created_at >= date_trunc('week', NOW())"
                );
            }

            // Filter this month's orders
            Some("month") => {
                query.push(
                    " AND orders.created_at >= date_trunc('month', NOW())"
                );
            }

            // No time filter
            _ => {}
        }   

        Ok(())
    }



    // ============================================================
    // PRODUCT FILTERS
    // Used for:
    // - low stock
    // ============================================================

    // Reusable product filter function
    fn apply_product_filters(
        query: &mut QueryBuilder<Postgres>,
        claim: &Claims,
    ) -> Result<(), CustomError> {

        // Apply product access rules based on user role
        match claim.role.as_str() {

            // Admin can see all products in company
            "admin" => {
                query.push(" AND company_info.company_name = ");
                query.push_bind(claim.companyname.clone());
            }

            // Manager can only see products from their branch
            "manager" => {
                query.push(" AND company_info.company_name = ");
                query.push_bind(claim.companyname.clone());

                query.push(" AND company_info.branch_name = ");
                query.push_bind(claim.branchname.clone());
            }

            // POS staff can only see products they own
            "pos_staff" => {
                query.push(" AND company_info.company_name = ");
                query.push_bind(claim.companyname.clone());

                query.push(" AND company_info.branch_name = ");
                query.push_bind(claim.branchname.clone());

                query.push(" AND products.user_id = ");
                query.push_bind(claim.id.clone());
            }

            // Reject unauthorized roles
            _ => {
                return Err(CustomError::Unauthorized);
            }
        }

        Ok(())
    }

    // Main dashboard business logic
    pub async fn dashboard(&self, claim: Claims, range: Option<String>) -> Result<serde_json::Value, CustomError> {
    
        // ── Step 1: Fetch totals summary ─────────────────────────────

        // Query for total revenue, order count, and average order value
        let mut  totals = sqlx::QueryBuilder::new(
            "SELECT
                COALESCE(SUM(total), 0)::float8           AS total_revenue,
                COUNT(*)::bigint                           AS total_orders,
                COALESCE(AVG(total), 0)::float8            AS avg_order_value
            FROM orders
            JOIN company_info ON orders.company_info_id = company_info.company_info_id"
        );

        // Apply reusable filters
        Self::apply_order_filters(
            &mut totals,
            &claim,
            &range,
        )?;

        // Execute totals query
        let totals_result: TotalsRow = totals
            .build_query_as::<TotalsRow>()
            .fetch_one(&self.pool)
            .await
            .map_err(|e| {
                eprintln!("Failed to fetch totals: {:?}", e);
                CustomError::DatabaseError
        })?;


        // ── Step 2: Fetch total items sold ──────────────────────────

        // Query total quantity sold
        let mut total_sold = sqlx::QueryBuilder::new(
        "SELECT COALESCE(SUM(order_items.quantity), 0)::bigint AS total_sold
            FROM order_items
            JOIN orders ON orders.orders_id = order_items.order_id
            JOIN company_info ON orders.company_info_id = company_info.company_info_id"
        );

        // Apply filters
        Self::apply_order_filters(
            &mut total_sold,
            &claim,
            &range,
        )?;

        // Execute query
        let total_sold_row: TotalSoldRow = total_sold
            .build_query_as::<TotalSoldRow>()
            .fetch_one(&self.pool)
            .await
            .map_err(|e| {
                eprintln!("Failed to fetch total sold: {:?}", e);
                CustomError::DatabaseError
        })?;

        // ── Step 3: Fetch top 5 products ────────────────────────────

        // Query top-selling products
        let mut top_products = sqlx::QueryBuilder::new(
            "SELECT
                products.product_name                              AS name,
                SUM(order_items.quantity)::bigint                    AS quantity,
                SUM(order_items.quantity * order_items.price)::float8         AS revenue
            FROM order_items
            JOIN products ON products.product_id = order_items.product_id
            JOIN orders ON orders.orders_id = order_items.order_id
            JOIN company_info ON orders.company_info_id = company_info.company_info_id"
        );

        // Apply filters
        Self::apply_order_filters(
            &mut top_products,
            &claim,
            &range,
        )?;

        // Group and limit results
        top_products.push(" GROUP BY products.product_name ORDER BY quantity DESC LIMIT 5");

        // Execute query
        let top_products_result: Vec<TopProduct> = top_products
            .build_query_as::<TopProduct>()
            .fetch_all(&self.pool)
            .await
            .map_err(|e| {
                eprintln!("Failed to fetch top products: {:?}", e);
                CustomError::DatabaseError
        })?;

        // ── Step 4: Fetch recent transactions ───────────────────────

        // Query latest orders
        let mut recent_transactions = sqlx::QueryBuilder::new(
            "SELECT
                orders.orders_id AS id,
                orders.created_at,
                orders.total::float8 AS total,
                COALESCE(SUM(order_items.quantity), 0)::bigint AS items
            FROM orders
            LEFT JOIN order_items ON order_items.order_id = orders.orders_id
            JOIN company_info ON orders.company_info_id = company_info.company_info_id"
        );

        // Apply filters
        Self::apply_order_filters(
            &mut recent_transactions,
            &claim,
            &range,
        )?;

        // Group and sort newest first
        recent_transactions.push(" GROUP BY orders.orders_id, orders.created_at, orders.total ORDER BY orders.created_at DESC LIMIT 10");
        
        // Execute query
        let recent_transactions_result: Vec<RecentTransaction> = recent_transactions
            .build_query_as::<RecentTransaction>()
            .fetch_all(&self.pool)
            .await
            .map_err(|e| {
                eprintln!("Failed to fetch recent transactions: {:?}", e);
                CustomError::DatabaseError
        })?;


        // ── Step 5: Fetch low stock products ────────────────────────

        // Query products with low stock
        let mut low_stock = sqlx::QueryBuilder::new(
            "SELECT product_name AS name, product_stock AS stock
            FROM products
            JOIN company_info ON products.company_info_id = company_info.company_info_id"
        );

        // Apply product filters
        Self::apply_product_filters(
            &mut low_stock,
            &claim,
        )?;

        // Sort lowest stock first
        low_stock.push(" AND product_stock <=10 ORDER BY product_stock ASC");

        // Execute query
        let low_stock_result: Vec<LowStockItem> = low_stock    
            .build_query_as::<LowStockItem>()
            .fetch_all(&self.pool)
            .await
            .map_err(|e| {
                eprintln!("Failed to fetch low stock products: {:?}", e);
                CustomError::DatabaseError
        })?;

        // ── Step 6: Return full dashboard response ──────────────────

        Ok(serde_json::json!(DashboardSummary {

            // Total revenue
            total_revenue: totals_result.total_revenue,

            // Total items sold
            total_quantity_sold: total_sold_row.total_sold,

            // Total order count
            total_sold: totals_result.total_orders,

            // Average order value
            avg_order_value: totals_result.avg_order_value,

            // Top-selling products
            top_products: top_products_result,

            // Recent orders
            recent_transactions: recent_transactions_result,

            // Low stock products
            low_stock: low_stock_result,
        }))
    }
    

}

//====================================================================




//=========================API ENDPOINTS==============================

// GET endpoint for dashboard data
#[get("/dashboard")]
pub async fn dashboard(

    // Query parameters from frontend
    query: web::Query<DashboardQuery>,

    // Shared application state
    service: web::Data<AppState>,

    // Incoming HTTP request
    req: HttpRequest,
) -> impl Responder {

    // Read JWT claims stored by authentication middleware
    let claims = match req.extensions().get::<Claims>().cloned() {

        // Claims found
        Some(c) => c,

        // Unauthorized if claims missing
        None => return HttpResponse::Unauthorized().body("Unauthorized"),
    };

    // Call dashboard service logic
    match service.dashboards.dashboard(claims,query.range.clone()).await {

        // Success response
        Ok(dashboardsummary) => HttpResponse::Ok().json(serde_json::json!({
            "message": "Dashboard fetched successfully",
            "data": dashboardsummary
        })),

        // Error handling
        Err(e) => match e {

            // Database error response
            CustomError::DatabaseError => {
                HttpResponse::InternalServerError().body(e.to_string())
            }

            // Unauthorized response
            CustomError::Unauthorized => {
                HttpResponse::Unauthorized().body(e.to_string())
            }

        }
    }
}

//====================================================================


